version: "3.7"

services:

  mongo:
    container_name: task_mongo
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: task
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb-data:/data/db

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: task_server
    restart: always
    ports:
      - 9000:8000
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
    links:
      - mongo
    networks:
      - default

volumes:
  task-mongodb-data:
networks:
  default:

